version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: "composer"
    directory: "/web"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
