name: bantu_pengusaha
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.0-91.0.dev <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter:
    sdk: flutter
  get_cli: ^1.8.1
  curved_labeled_navigation_bar: ^2.0.2
  oktoast: ^3.4.0
  curved_navigation_bar: ^1.0.3
  http: ^1.2.1
  shared_preferences: ^2.2.2
  location: ^5.0.3
  dio: ^5.4.1
  google_maps_flutter: ^2.6.0
  syncfusion_flutter_maps: ^25.1.35
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  uses-material-design: true
