services:
    db:
        image: mysql:8.3
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: bp
            MYSQL_USER: matt
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        volumes:
            - "db_data:/var/lib/mysql"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        depends_on:
            - db
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: password
        ports:
            - "8080:80"

volumes:
    db_data:
